language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
 - mysql -e 'create database isosceles_tests'
 - mysql isosceles_tests < ./install/sql/build-db_mysql.sql
 - cp libs/config.sample.inc.php libs/config.inc.php
 - cp tests/config.sample.inc.php tests/config.tests.inc.php
 - mkdir libs/data
 - chmod -R 777 libs/data

script: php tests/all_tests.php